sonar.host.url=http://host.docker.internal:9000
sonar.projectKey=backend
sonar.token=sqp_2634afcd490dd9f8547235a692bd5f8ea0b0a08e
    
sonar.sources=.
sonar.exclusions=**/*_test.go
    
sonar.tests=.
sonar.test.inclusions=**/*_test.go